spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ielts
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  default-admin:
    username: admin
    password: admin
